name: Check formatting and linting

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  check-formatting-and-linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[development]
      - name: Format and lint
        run: sqlmodel-yaml-format-and-lint --test
